name: alltask
on:
 push:
  - develop
  - release
  - main
 jobs:
  name: develop
   runs-on: windows-latest
   steps:
    -name: printdevelopjob
     run: echo " its develop job"
   name: release
    runs-on: windows-latest
    steps: 
     - name: printreleasejob
       run: echo " its release job"
   name: main
    runs-on: windows-latest
    steps:
     - name: printmainjob
       run: echo "its main job"
