name: alltask
on:
 push:
  - develop
  - release
  - main
 jobs:
  develop:
   runs-on: windows-latest
   steps:
    - name: printdevelopjob
      run: echo "its develop job"
  release:
   runs-on: windows-latest
   steps: 
    - name: printreleasejob
      run: echo " its release job"
  main:
   runs-on: windows-latest
   steps:
    - name: printmainjob
      run: echo "its main job"
