name: task1
on:
 push:
  branches: [develop]
 workflow_dispatch:  
jobs:
 mydetails:
  runs-on: windows-latest
  steps:
   - name: getsecreatid
     run: |
      echo "the secreat would be covered"
      echo ${{secrets.MY_REPO_ID}}
   - name: person-details
     run: | 
       echo "my surname is madamanchi"
       echo "my name is swarupa Rani"

 edudetails:
  needs: mydetails
  runs-on: windows-latest
  steps:
   - name: myeducation
     run:
      echo "i completed masters in computer applications"
 emp_details:
  needs: [mydetails,edudetails]  
  runs-on: windows-latest
  steps:
   - name: employee
     run: |
      echo " empid: 462059"
      echo " emailid: madamanchi.swarupa-rani@capgemini.com"
      echo "grade : B1"   

